title: Offer
type: object

properties:
  title: { type: string }

  intro:    { $ref: "#/definitions/intro" }
  about:    { $ref: "#/definitions/about" }
  pricing:  { $ref: "#/definitions/pricing" }
  features: { $ref: "#/definitions/features" }
  authors:  { $ref: "#/definitions/authors" }
  reviews:  { $ref: "#/definitions/reviews" }
  form:     { $ref: "#/definitions/form" }

required: [title]
additionalProperties: false

definitions:

  button:
    type: object
    properties:
      text:   { type: string }
    required: [text]
    additionalProperties: false

  titledtext:
    type: object
    properties:
      title:  { type: string }
      text:   { type: string }
    required: [title, text]
    additionalProperties: false

  intro:
    type: object
    properties:
      title:  { type: string }
      text:   { type: string }
      button: { $ref: "#/definitions/button" }
    required: [title, text, button]
    additionalProperties: false

  about:
    type: object
    properties:
      title:    { type: string }
      subtitle: { type: string }
      items:
        type: array
        items: { $ref: "#/definitions/titledtext" }
    required: [title, items]
    additionalProperties: false

  review:
    type: object
    properties:
      picture: { type: string, format: uri }
      title:  { type: string }
      text:   { type: string }
    required: [picture, title, text]
    additionalProperties: false

  reviews:
    type: object
    properties:
      title:    { type: string }
      subtitle: { type: string }
      items:
        type: array
        items: { $ref: "#/definitions/review" }
    required: [title, items]
    additionalProperties: false

  price:
    type: object
    properties:
      price:    { type: string }
      title:    { type: string }
      subtitle: { type: string }
      features: { type: array, items: { type: string } }
      button:   { $ref: "#/definitions/button" }
    required: [price, title, features, button]
    additionalProperties: false

  pricing:
    type: object
    properties:
      title:    { type: string }
      subtitle: { type: string }
      items:
        type: array
        items: { $ref: "#/definitions/price" }
    required: [title, items]
    additionalProperties: false

  author:
    type: object
    properties:
      name:  { type: string }
      title:  { type: string }
      text:   { type: string }
      button: { $ref: "#/definitions/button" }
    required: [name, title, text, button]
    additionalProperties: false

  authors:
    type: object
    properties:
      title:    { type: string }
      subtitle: { type: string }
      items:
        type: array
        items: { $ref: "#/definitions/author" }
    required: [title, items]
    additionalProperties: false

  feature:
    type: object
    properties:
      title:  { type: string }
      text:   { type: string }
    required: [title, text]
    additionalProperties: false

  features:
    type: object
    properties:
      title:    { type: string }
      subtitle: { type: string }
      items:
        type: array
        items: { $ref: "#/definitions/feature" }
    required: [title, items]
    additionalProperties: false

  form:
    type: object
    properties:
      title:    { type: string }
      subtitle: { type: string }
      text:     { type: string }
    required: [title, text]
    additionalProperties: false
