title: Offer
type: object

properties:
  title: { type: string }

  sections:
    type: array
    items:
      type: string
      enum: [intro, about, pricing, features, authors, reviews, form]

required: [title]
additionalProperties: false